# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Projects Studio
email: libvisualization@umich.edu 
repository: clarkdatalabs/clarkdatalabs.github.io
description: > # this means to ignore newlines until "baseurl:"
  List past and ongoing projects of the Digital Processing Studio at the University of Michigan.
  
#baseurl: "/index.html" # the subpath of your site, e.g. /blog
url: "https://clarkdatalabs.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

#social
#facebook: http://facebook.com/webjeda
#quora: http://quora.com/sharathdt
#twitter: http://twitter.com/@webjeda
github: http://github.com/clarkdatalabs


# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

